application: uchicago-tkompare-drivercheck
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /css
  static_dir: css
- url: /fonts
  static_dir: fonts
- url: /img
  static_dir: img
- url: /js
  static_dir: js